const projects = [
  {
    id: 1,
    title: "Tapis Rouges",
    description: "Developed a comprehensive restaurant website as part of a front-end internship, showcasing my skills in HTML, CSS, and JavaScript. The website consists of seven pages, each serving a unique purpose to enhance the user experience.",
    image: require('./images/Tapis_rouges.png'),
    liveDemoLink: "https://agitated-swanson-b1aba5.netlify.app/",
    githubLink: "https://github.com/Imziyasser00/Tapis-Rouges",
    technologies: ["HTML", "CSS", "JAVASCRIPT"],
    KeyFeatures: [
      "Engaging User Interface",
      "Online Ordering Functionality",
      "Team Showcase",
      "Interactive Gallery",
      "Contact Form"
    ],
  },
  {
    id: 2,
    title: "Let's Do It",
    description: 'Immerse yourself in a cutting-edge T-shirt customization experience with our ThreeJs-powered platform. Unleash your creativity by dynamically changing T-shirt colors, exploring smooth mouse-driven movements, and personalizing your apparel with uploaded logos and textures. Elevate your fashion game in real-time!',
    image: require('./images/3DTShirt.png'),
    liveDemoLink: "https://serene-dasik-eb2298.netlify.app/",
    githubLink: "https://github.com/Imziyasser00/threeJs-website",
    technologies: [
      "React",
      "ThreeJs",
      "HTML",
      "CSS",
      "JavaScript",
      "Vite",
      "Tailwind CSS",
      "ESLint",
      "PostCSS",
    ],
    KeyFeatures: [
      "T-shirt color customization",
      "Fluid mouse-controlled T-shirt movement",
      "Seamless logo and texture uploading",
    ],
  },
  {
    id: 3,
    title: "Weather PWA",
    description: 'A progressive web app for checking the weather forecast.',
    image: require('./images/PWA.png'),
    liveDemoLink: "https://astounding-pothos-aad407.netlify.app/",
    githubLink: "https://github.com/Imziyasser00/PWA_FIRST_APP",
    technologies: ["React", "Axios"],
    KeyFeatures: [
      "PWA functionality (offline support, add to home screen)",
      "Real-time weather updates",
      "User-friendly interface",
      "Responsive design",
      "Integration with a weather API (using Axios)"
    ],
  },
  {
    id: 4,
    title: "AI Article Summarizer",
    description: 'Unlock the power of instant comprehension with our Summarizer. Effortlessly distill lengthy content into concise summaries, saving you time and delivering the essence of information. Simplify complexity and stay informed at a glance.',
    image: require('./images/summarizer.png'),
    liveDemoLink: "https://65c8f7a651792f3b9dfbd81b--idyllic-dolphin-5b9ec6.netlify.app/",
    githubLink: "https://github.com/Imziyasser00/AISummarizer_website",
    technologies: ["React", "@mantine/core", "@mantine/hooks", "@reduxjs/toolkit", "react-icons", "react-loader-spinner", "react-redux"],
    KeyFeatures: ["Real-time Updates", "Search Functionality", "Responsive Design", "Integration with APIs"],
  },
  {
    id: 5,
    title: "Car Showcase",
    description: 'Car Showcase is a cutting-edge Next.js project that redefines the car renting experience. Browse a curated selection of top-tier vehicles, enjoy seamless navigation, and effortlessly book your dream car for an unforgettable journey. Elevate your travel experience with Car Showcase – where luxury meets convenience.',
    image: require('./images/Car-showasing.png'),
    liveDemoLink: "https://65d213448f9c515cde8e69b8--car-showcasing.netlify.app/",
    githubLink: "https://github.com/YassirImzi/car-showcasing-app",
    technologies: ["headlessui", "next", "react", "react-dom", "sharp", "typescript", "tailwindcss", "typescript"],
    KeyFeatures: ["Real-time Updates", "Search Functionality", "Responsive Design", "Integration with APIs"],
  },
  {
    id: 6,
    title: "PopCorn",
    description: "Discover your next favorite movie with PopCorn! This website recommends movies through an infinite scroll, providing brief details, posters, ratings, and release dates. Immerse yourself in the world of cinema and find the perfect film for your mood.",
    image: require('./images/popcorn.png'),
    liveDemoLink: "https://65d63b63b1e8efe586808cf6--thriving-cocada-164f97.netlify.app/",
    githubLink: "https://github.com/YassirImzi/Films-Listing-Website",
    technologies: ["React", "Framer Motion", "Material-UI", "API", "Infinite Scroll"],
    KeyFeatures: [
      "Infinite Scroll of Movie Recommendations",
      "Short Movie Briefs",
      "Poster Display",
      "Rating Information",
      "Release Date",
    ],
  },
  {
    id: 7,
    title: "Massage Gun",
    description: "A product presentation website for a massage vibrator designed for athletes. Implemented clean and elegant code using React, Tailwind CSS, and Framer Motion.",
    image: require('./images/massage-gun.png'),
    liveDemoLink: "https://65e05aba423445ede947e7e5--glistening-cuchufli-566b71.netlify.app/",
    githubLink: "https://github.com/YassirImzi/Product-Website",
    technologies: ["React", "Tailwind CSS", "Framer Motion"],
    KeyFeatures: [
      "Clean and Elegant Design",
      "Product Presentation",
      "Responsive UI",
      "Speed Optimization",
    ],
  },
  {
    id: 8,
    title: "E-scooter Marketing Website",
    description: "Developed a marketing website for promoting e-scooters, leveraging ReactJS for frontend development and Tailwind CSS for styling. Implemented user authentication using Clerk to provide secure access to exclusive content and features.",
    image: require('./images/E-scooter.png'),
    liveDemoLink: "https://6607ff509a3fbb9a421d49b9--dynamic-platypus-92be49.netlify.app/",
    githubLink: "https://github.com/Imziyasser00/E-Scooter-Marketing-Website",
    technologies: ["React", "Tailwind CSS", "Clerk", "Vite"],
    KeyFeatures: [
      "User Authentication with Clerk",
      "Promotional Content Display",
      "Responsive Design",
    ],
  },
  {
    id: 9,
    title: "Welcome to Morocco",
    description: "Developed a website that showcases the top 15 cities in Morocco, providing detailed information for each city: introduction, slider images, historical info, updated weather using API, population, area surface, timezone, languages, city culture tips, travel info, points of interest, events, and a map of the city. All this is animated using GSAP.",
    image: require('./images/Morocco.png'),
    liveDemoLink: "https://6653c24930bad9dec9e617eb--luminous-bubblegum-0a2b62.netlify.app/",
    githubLink: "https://github.com/Imziyasser00/Morocco-website-ReactJs-tailwindCss-Gsap",
    technologies: ["ReactJS", "Tailwind CSS", "AntD", "Axios", "SliderJS"],
    KeyFeatures: [
      "Detailed city information",
      "Slider images",
      "Updated weather using API",
      "Population and area surface",
      "Timezone and languages",
      "City culture tips",
      "Travel info",
      "Points of interest",
      "Events",
      "City map",
      "GSAP animations"
    ],
  }
];

export default projects;
