// src/data/projectsData.js
const projects = [
    {
      id:1,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies: ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },{
      id:2,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
    {
      id:3,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
    {
      id:4,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
    {
      id:5,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
    {
      id:6,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
    {
      id:7,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
    {
      id:8,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
    },
    {
      id:9,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
    {
      id:10,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
    {
      id:11,
      title: "Let's Do It",
      description: 'ThreeJs T-shirt custom Designer.',
      image: 'https://blog.hubspot.com/hs-fs/hubfs/free-website-builders_1.webp?width=650&height=412&name=free-website-builders_1.webp',
      liveDemoLink: "",
      githubLink: "",
      technologies : ["HTML","CSS","JAVASCRIPT"],
      KeyFeatures: ["User Authentication","Real-time Updates","Search Functionality","Responsive Design","Integration with APIs"],
    },
  ];
  
  export default projects;
  